services:
  app:
    container_name: netRSS
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "15001:15001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:15001
    volumes:
      - ./database:/app/app/Data
      - ./CHANGELOG.md:/app/CHANGELOG.md
      - keys-volume:/root/.aspnet/DataProtection-Keys
    restart: always

volumes:
  keys-volume:
